# Generated by Django 2.0.3 on 2018-04-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20171229_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
